### ISSUE TITLE
Capacitor support

### ISSUE THREAD

**Issue by idhard** [auth0/auth0-cordova#104]
Hello , would like to know if the library support [Capacitor](https://capacitor.ionicframework.com/) or if somebody made it work . I have followed the steps  on the docs : https://auth0.com/docs/quickstart/native/cordova/01-login but everytime i try to login  the authorization method return "user canceled". thanks!

**Comment by WorldMaker** [comment]
Capacitor "should be" easy because you don't need the two dependent plugins: Capacitor has deep links and in-app browser "built in". Additionally, Capacitor by default routes "external links" to external browsers automatically so it may only be the deep link functionality that matters if the external browser is fine (but code to use the in app browser should be easy).

Though I haven't got it working yet. I'm also wondering if I could get away with using Universal Links for the callback and then the callback URL may even be the same for both mobile and web.

It would be great if there was official Auth0 guidance, though.

**Comment by idhard** [comment]
finally i implemented auth0 universal login embedded in a web view , you need to have custom domains to do it but it did the trick . I gave up with external links as Auth0 doesn't support custom schemas in their configurations only http & https, Capacitor define the schemas like "capacitor://" making imposible to make it work ... except if i'm missing something

**Comment by WorldMaker** [comment]
@idhard The `capacitor://` addresses are the server internal to the app on iOS only and not addressable outside of the app. You need to add it to Allowed Origins in Auth0 if making AJAX calls from the app on iOS. (I haven't yet figured out Android's origins, but it doesn't appear to be `capacitor://` though.) To setup a custom schema for iOS you have to set it up in the PLIST files, and that would be whatever you set it to, but you could use that as a callback outside the app then. (Which is what you need for Auth0 callbacks.)

**Comment by WorldMaker** [comment]
In case it is useful for anyone following this thread, my gut seems to be correct that this can be done in Capacitor using the built-in plugins. I've got iOS login working (and trying to debug Android now). I can't share my code at this point, but some notes:

* Converted my app to always use the PKCE flow (instead of WebAuthentication). Used this repository and a couple other "Auth0 SPA PKCE" samples I found for guidance. In my case one of the surprising trip-ups was needing a fallback SHA-256 library for some browsers/scenarios, and not just relying on the modern `window.crypto.subtle.digest()`, though I am preferring that when available. This was probably where most of the subtle bugs I had to deal with came from as Auth0's WebAuthentication library does so many things under the hood automatically and finding the PKCE equivalents was sometimes so surprising. Another thing that I found I preferred was using `sessionStorage` for PKCE code verifiers (which I found in one of the more recent PKCE samples) instead of callback closures (which is found in the repository here).
* `buildAuthorizeUrl` and then pass that into the Capacitor `Browser.open({ url })`, the built-in In-App Browser works fine. I wrapped that call in a `Capacitor.isNative` check to use `window.location.assign(url)` as a fallback instead of the web version of the plugin's new tab behavior.
* Set up the custom callback scheme in Info.plist for iOS, under `URL Types`. (In my case to setup `com.example.bundle.identifier://` add the URL scheme `com.example.bundle.identifier` for URL identifier that matches the bundle identifier.) Use `App.addListener('appUrlOpen', ...)` and `App.getLaunchUrl()` to convert that into internal app addresses. (I found that I easily connected it to react router `props.history.push()` in a component for full deep linking support on the custom scheme.) Auth0 doesn't seem to validate URLs for callbacks that don't have a "hostname" in the dashboard, but since I plugged it into the application's page routing I just created a direct link to my authorization callback page as the callback URL. (`com.example.bundle.identifier://pkce` where `/pkce` is the callback page)

**Comment by nseb** [comment]
@WorldMaker can you share your code ?

**Comment by WorldMaker** [comment]
@nseb Unfortunately my app is proprietary and not something I can share directly. [My notes above](https://github.com/auth0/auth0-cordova/issues/104#issuecomment-518813084) remain about as exhaustive as I can get in describing the solution that worked for me. If it helps, the hard parts are Configuration more than they are Code. You can test PKCE flow in dev in the browser and some Auth0 documentation is even recommending it for SPAs today. After that the hard part is making sure you've got custom URLs configured appropriately for each respective platform. In the Capacitor model that configuration is entirely on you, rather than plugins, and you may have to research how to make the changes you need in the respective PLIST and Gradle files, etc, but there you can rely on most native development tutorials for those changes.

**Comment by bobbydowling** [comment]
@WorldMaker Any way you can share only the relevant parts of your working code... or maybe some pseudo code if possible? Certainly appreciate your code descriptions, just not enough for this newbie to Capacitor/Cordova/mobile dev...

**Comment by WorldMaker** [comment]
@bobbydowling Sorry, I really do think that all of the relevant code/pseudo-code is [in the above comment](https://github.com/auth0/auth0-cordova/issues/104#issuecomment-518813084). Reviewing I think that the only thing it's missing is that I mention but fail to directly like the [Auth0 PKCE SPA sample](https://github.com/auth0/spa-pkce) which was my starting point for most of the code. (I cleaned it up to use async/await and a couple polyfills I mention in the above comment.)

The [Auth0 PKCE documentation](https://auth0.com/docs/flows/concepts/auth-code-pkce) which references that SPA sample (and is referenced by it) may also be helpful.

**Comment by WorldMaker** [comment]
Perhaps if there's a more specific question or thing not working I might have a better idea of how to help?

**Comment by ErHarinderSingh** [comment]
> Perhaps if there's a more specific question or thing not working I might have a better idea of how to help?

Can u help me to make it workable using Capacitor ?

**Comment by brassier** [comment]
@WorldMaker - Can you tell us if your solution opened the login page inside the app, or outside the app (new window)?  I am able to get the SPA SDK to work within a Capacitor app with the login page being in a new window.  I would love for the login page to stay within the app if possible, but I keep getting variations of Auth0 errors when I attempt that: 
- Issues getting protocol from custom URL scheme
- Issues with origin_mismatch 

I'm not sure why the external window does not have these problems.  The one difference is having the auth0 URL in the capacitor `server.allowNavigation` settings (which opens it in app).

**Comment by brassier** [comment]
In case others have the issue I noted above, I found my issue:
https://stackoverflow.com/questions/66591207/capacitor-in-app-navigation-custom-url-redirect
