### ISSUE TITLE
Refresh tokens

### ISSUE THREAD

**Issue by jdnichollsc** [auth0/auth0-cordova#120]
Hello guys, I was wondering if we can support refresh tokens with this npm package to generate a new access token

Thanks in advance!

**Comment by Widcket** [comment]
Hi @jdnichollsc, currently we don’t have a recommended approach for using refresh tokens in Cordova. That said, if you wish to obtain a refresh token, you can add the `offline_access` scope to the authentication call. That refresh token can then be used to get new access and ID tokens by [making a request](https://auth0.com/docs/tokens/guides/use-refresh-tokens) to the `/oauth/token` endpoint.

**Comment by jdnichollsc** [comment]
@Widcket Hi Rita, I was wondering how can I get the params to use that endpoint with a request? As I know when you use PKCE, a code challenge is required and that values are generated internally
Also, we can't use refresh tokens from SPA, so only native code can access that
Thanks in advance

**Comment by stevehobbsdev** [comment]
Hi @jdnichollsc 

As this library uses [`auth0-js`](https://github.com/auth0/auth0.js) under the hood, by default it uses the [implicit flow](https://auth0.com/docs/flows/concepts/implicit) rather than Auth Code + PKCE. Unfortunately we do not issue refresh tokens to requests that are using the implicit flow, for security.

As such, if you are specifying parameters that would instead initiate a PKCE flow then you must be calculating the code challenge and verifier yourself, which means that you would be able to send the challenge in a call to `/token`.

It might be useful to see how you are configuring the SDK to get a better picture of what you're working with.

**Comment by jdnichollsc** [comment]
In my current project, we're working with RN and I configued PKCE using an Okta package https://www.npmjs.com/package/@okta/okta-react-native
I'm checking if there're options too for hybrid apps using Cordova :)

**Comment by giulianok** [comment]
@stevehobbsdev any idea if there's a plan to migrate from auth0-js to auth0-spa-js? are there any limitations preventing it?

**Comment by stevehobbsdev** [comment]
@giulianok We don't have any plans to make that change I'm afraid. We're instead potentially looking at how our Ionic samples and such can make use of something like `auth0-spa-js` directly rather than using this package.

As I said though, no plans to share on that as such I'm afraid.
