### ISSUE TITLE
iOS social provider signout problem

### ISSUE THREAD

**Issue by gregor-srdic** [auth0/auth0-cordova#121]
### Description
On iOS device, when user signs in using social provider (facebook or google) and then signs out - the next time he tries to sign in again using the same social provider, he is not able to enter the email and password again (and potentially use different google/facebook account), instead he is automatically signed in using the same account as he entered the first time.

### Reproduction

* sign in using specific google account (enter username and password)
* sign out
* try to sign in with a different google account

### Environment
-  auth-cordova 0.4.2
- Ionic4, Angular8
- iOS 12

**Comment by Widcket** [comment]
Hi @gregor-srdic, to perform logout at the [identity provider layer](https://auth0.com/docs/logout/guides/logout-idps), you need to make a request to the `/v2/logout` [endpoint](https://auth0.com/docs/api/authentication#logout) including the `federated` parameter. Note that federated logout is up to each identity provider, so the behavior may be inconsistent.
Since auth0-cordova depends on **auth0.js**, you can import and use it directly to [build the url](https://github.com/auth0/auth0.js/blob/master/test/authentication/authentication.test.js#L233) to make the request to.

**Comment by gregor-srdic** [comment]
@Widcket thanks a lot for the hint about the `federated` parameter, however I am facing a problem:

based on the cordova example from auth0 documentation, I open the logout url in a safariviewcontroller plugin but after I included the `federated` parameter, the popup window redirects to facebook page and does not close (return to the app):
``` if (this.isCordova) {
      const url = this.getRedirectUri('logout');
      // https://{{domain}}/v2/logout?federated&client_id={{clientId}}&returnTo={{packageId}}://{{domain}}cordova/{{packageId}}/callback
      this.utils.openWebPage(url);
    } ```

**Comment by Widcket** [comment]
@gregor-srdic we had a bug on the sample app, check out the fix: https://github.com/auth0-samples/auth0-cordova-samples/pull/41/files
