### ISSUE TITLE
IOS: Login screen hangs after entering credentials

### ISSUE THREAD

**Issue by dtaalbers** [auth0/auth0-cordova#58]
I've followed the basic setup instructed [here](https://auth0.com/docs/quickstart/native/ionic2/01-login). On an Android device logging in works fine, but when deploying to my iPhone 5s (iOS 11.0.3) it just keeps loading after entering my credentials and pressing 'login'.

Any idea on what the cause can be? I've used the example app provided by the above instructions. You can grab it [here](https://www.dropbox.com/s/rsg6jqwj8rkne9r/01-login.zip?dl=0). Note that I have removed the used auth0 settings and app identifier (had to change it to one of my own to be able to deploy it to my iOS device.

UPDATE:

It looks like that [this](https://github.com/auth0/auth0-cordova/blob/master/src/agent/browser.js#L19) callback is not triggered after entering the credentials and logging in.

**Comment by ollyjohn** [comment]
I and my colleagues have a similar issue where we are faced with a seemingly perpetual loading animation where an error is returned from the login attempt.  

We are able to get the error back from the onRedirectUri method, but the safari view is never destroyed (note that I have tried to manually `hide()` it but this causes issues with auth0 because it doesn't actually get rid of the session.

Any advice on this would be much appreciated as it's quite a significant issue for us at the moment.

**Comment by mohpra** [comment]
I also had the same issue. I tried using ionic-deeplinks-plugin instead of cordova-plugin-customurlscheme.

In app.component.ts do the following:

    this.deeplinks.route({
    }).subscribe((match) => {
        Auth0Cordova.onRedirectUri(match.$link.url);
    }, (nomatch) => {
        Auth0Cordova.onRedirectUri(nomatch.$link.url); 
    });

It works fine after this.

However I am also using cordova-plugin-linkedin for native linked login. And their seems to be a problem when this plugin as well as ionic-deeplinks-plugin is used. 

Any idea why this is happening?

**Comment by ahmadao** [comment]
Why no one is fixing this?

**Comment by victororlyk** [comment]
the same issue with react ionic
