### ISSUE TITLE
Logout from Facebook IdP

### ISSUE THREAD

**Issue by WinGood** [auth0/auth0-cordova#86]
Hello everyone, could you please help me?

I want to add logout functionality from Facebook IdP into my application. I found how I can implement this in auth0 [documentation](https://auth0.com/docs/logout#facebook-users) it works great in the browser (desktop), but for cordova application it's not working. I don't know why, but I still see “confirm login” screen on the facebook after logout.

**Login:**
```
private auth0Cordova = new Auth0Cordova({
  clientId: '',
  domain: '',
  callbackURL: window.location.href,
  redirectUri: window.location.href,
  packageIdentifier: ''
});

this.auth0Cordova.authorize({
  'facebook',
  prompt: false,
  scope: 'openid profile email user_metadata picture offline_access'
}, (err, authResult) => {});
```

**Logout:**
```
const accessToken = 'facebook_access_token';
const url = `https://login-staging.songline.fm/v2/logout?federated&returnTo=https%3A%2F%2Flogin-staging.songline.fm%2Flogout%3FreturnTo%3Dhttps%3A%2F%2Fstaging.songline.fm&access_token=${accessToken}`;

var options = {
  hidden: false,
  url
};

window.SafariViewController.show(
  options,
  function(result) {},
  function(message) {}
);
```

![image](https://user-images.githubusercontent.com/6697977/39710838-2688ec58-5248-11e8-8179-4bb07e5025de.png)

**Comment by darkyen** [comment]
On a mobile there are multiple layers of logout. 

1. The application session. 
2. The IdP Session.
3. The Session at Auth0.

Since SFSafariViewController behaves differently then ChromeCustomTabs, if you use `/v2/logout` by using the lower level plugin `SFSafariViewController`. It'll kill the user's facebook session entirely on the device. An alternative approach in this case can be to pass `prompt=login` which will force reauthentication if supported by the IdP.
